### ISSUE TITLE
Chrono doesn't differ between time/datetime/interval/timestamp

### ISSUE THREAD

**Issue by KGOH** [HealthSamurai/chrono#22]
This creates some logical problems:
- Should intervals which are greater than 4 years use leap years or every year should be 365 days
- Addition of two values may be ambiguous when both values look like dates which doesn't make sense & situations like that

This can be made by `:type` key in a value or metadata

This would be cool if we had ability to make assumptions about type of values without explicit type:
```
a + interval = a
a - a = interval
a - interval = a
```
When 
`a + a = a` ;  assume the right operand is interval using tz of left operand
`interval - a  = interval` ; assume `a` is an interval too ignoring tz

We want to have such types:
- datetime
- datetimetz
- interval

And maybe:
- timestamp (maybe just int instead of hashmap)
- date
- time
- datetz
- timetz

**Comment by Flawless** [comment]
When you adding 1 or more years to date you except to receive same date with increased day. Same for months. No matter have year leap day or not.
Adding and subtracting days, hours, minutes, seconds and seconds fractures have different logic.
According this in sql92 implemented with two different types: year-month and day-second.
If we want have intervals that includes all values from year to seconds, I think there is only one way - use astronomical year length with ~365.25, but real problems will start when we we want know, how much days in month. 365.25/12?

**Comment by KGOH** [comment]
I think in some cases this can be done easy without caring about days at all:
For example:
```
(ch/+ {:type date, :year 2020}
      {:type interval, :year 10})
;; => {:type date, :year 2030}
```
The problem may arise when the result type should be interval, which we have to normalize

**Comment by Flawless** [comment]
```sql
postgres=# SELECT date_part('epoch', INTERVAL '1 year') / (60*60*24) days;
  days
--------
 365.25
(1 row)
```

**Comment by KGOH** [comment]
And what to do when in the result of `date`+`interval` we have value with fractional year value? Coerce to int with ceiling?

**Comment by Flawless** [comment]
I can't find now about psql math, but it seems under the hood it combines year-month and day-seconds intervals:
```sql
postgres=# SELECT INTERVAL '0.3 year';
 interval
----------
 3 mons
(1 row)

postgres=# SELECT INTERVAL '1.33123123125195721 year';
   interval
---------------
 1 year 3 mons
(1 row)

postgres=# SELECT INTERVAL '1.33123123125195721 year 1 hour';
        interval
------------------------
 1 year 3 mons 01:00:00
(1 row)
```
There is no clear way to translate years to seconds or vice versa, so for most situations we may do like in psql and for exceptions - user may manually take epoch from interval and add or subtract it from date. I think most time people except round dates like when calculating age or guarantee period.
Also normalizing dates and intervals can't have same logic, cause we know when calendar started, but can't suggest it about intervals.

**Comment by KGOH** [comment]
I think interval math should be made as separate issue. And in this issue we can simply ignore interval difference from date for now. I'll create another issue for intervals

**Comment by KGOH** [comment]
I think for now we can use just use day-second intervals and later as a separate issue create day-month interval support, because day-month intervals are too big design problem on its own

**Comment by KGOH** [comment]
As for assumptions on type. I think we need to have function which returns value's possible types:
```
(guess-type {:month 7 :day 5}) ;; => #{:date :interval}
(guess-type {:month 7 :day 5 :tz 0}) ;; => #{:datetimetz}
```
